
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 103
#define YY_END_OF_BUFFER 104
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[310] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  104,  102,
      100,   98,  102,  102,  102,   17,   21,  102,   44,   45,
       13,   11,   50,   12,   53,   15,    9,    9,   51,   52,
       25,   31,   24,   18,   96,   96,   96,   96,   46,   60,
       47,   29,    8,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   48,
       28,   49,   30,    1,  103,    2,    3,    4,    5,   23,
        0,   97,    0,    0,    0,    0,   99,   36,   38,    0,
        0,   97,    0,    0,   14,   34,   32,   33,   54,   10,
       16,   35,   10,    9,    0,    0,    0,    0,    0,    0,

        9,    0,   43,   20,   27,   22,   26,   19,   56,   96,
       96,   96,   96,  101,   40,   96,   96,   81,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   93,
       96,   69,   74,   96,   96,   94,   96,   96,   96,   96,
       96,   96,   96,   96,   39,   97,    0,   97,    0,   97,
       37,   10,    0,   55,    0,    9,    0,    0,   10,    9,
        0,    9,    0,    9,    0,    9,   41,   42,   96,   96,
       96,   96,   96,   96,   76,   96,   96,   96,   96,   96,
       96,   82,   87,   96,   96,   96,   96,   78,   96,   96,
       96,   96,   96,   89,   96,   96,   96,   96,   96,   80,

       96,   96,   96,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   10,    0,   96,   66,   71,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   92,   63,   96,
       96,   83,   96,   96,   96,   96,   65,   96,   96,   96,
       96,   96,   90,   96,    0,    0,    0,    0,    0,    0,
       61,   96,   96,   96,   96,   91,   62,   67,   72,   96,
       96,   96,   96,   96,   96,   96,    7,   70,    6,   96,
       85,   95,   97,    0,    0,    0,    0,    0,    0,    0,
        0,   96,   96,   96,   86,   96,   68,   96,   88,   64,
       79,   96,   75,   97,    0,   97,    0,   96,   96,   96,

       96,   73,   96,   59,   58,   57,   77,   84,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,    1,   28,   29,   30,   29,   29,   31,   32,
       33,   33,   33,   33,   33,   33,   33,   34,   35,   33,
       33,   33,   33,   36,   33,   33,   33,   37,   33,   33,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   33,   52,   53,   54,   55,
       56,   57,   33,   58,   59,   60,   61,   33,   62,   63,
       64,   33,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[69] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    4,    4,    4,    4,    4,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[314] =
    {   0,
        0,    0,  908,  907,   67,   68,   69,   70,  908, 1000,
     1000, 1000,  881,  107,  904,  879,  878,  172, 1000, 1000,
       60,  877, 1000,   48,   62,   59,  224,  231,  876, 1000,
       62,  875,   63,  874,    0,  856,  842,  839, 1000,  894,
     1000,  864,  847,   36,  830,   40,  840,   39,   43,  833,
       49,  842,  828,  825,  199,  213,  824,   55,  824, 1000,
      848, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
      867,  866,  857,  829,  261,  711, 1000, 1000, 1000,  702,
      701,  700,  683,  237,  682, 1000, 1000, 1000, 1000,  255,
      681, 1000,  262,  279,  286,  250,  315,  269,  664,  293,

      321,  303, 1000,  679, 1000, 1000, 1000,  678, 1000,    0,
      650,  647,  640, 1000, 1000,  240,  654,  115,  656,  651,
      654,  641,  279,  213,  650,  639,  635,  636,  630,    0,
      628,    0,    0,  630,  284,    0,  624,  631,  265,  621,
      616,  628,  618,  624, 1000, 1000,  367,  664,  434,  659,
     1000,  484,  326, 1000,  334,  488,  299,  338,  490,  497,
      330,  626,  613,  502,  521,  534, 1000, 1000,  592,  598,
      597,  588,  599,  598,    0,  593,  584,  587,  594,  577,
      575,    0,    0,  586,  586,  585,  588,    0,  576,  585,
      572,  583,  573,    0,  566,  569,  559,  568,  555,    0,

      562,  564,  560,    0,    0,  581,  586,  355,    0,    0,
      649,  585,  356,  515,  526,  563,    0,    0,  552,  551,
      547,  542,  546,  523,  528,  520,  527,    0,    0,  520,
      522,    0,  531,  515,  526,  515,    0,  510,  522,  520,
      508,  517,    0,  516,  555,  717,    0,  550,    0,  785,
        0,  499,  503,  503,  469,    0,    0,    0,    0,  473,
      467,  472,  467,  454,  470,  456,    0,    0,    0,  444,
        0,    0, 1000,    0,  853,  408,  364,    0,  921,  406,
      431,  325,  322,  288,    0,  243,    0,  221,    0,    0,
        0,  236,    0,  259,  232,  239,  211,  130,   72,   65,

       53,    0,   25,    0,    0,    0,    0,    0, 1000,  989,
      993,  995,   73
    } ;

static const flex_int16_t yy_def[314] =
    {   0,
      309,    1,  310,  310,    1,    1,    1,    1,  309,  309,
      309,  309,  309,  309,  311,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  312,  312,  312,  312,  309,  309,
      309,  309,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
       14,  309,   14,  309,   14,  311,  309,  309,  309,   18,
       18,  309,  309,   18,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  313,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  312,
      312,  312,  312,  309,  309,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  309,  309,  309,   14,  309,   18,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  313,  313,  309,  309,  309,  309,  309,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  147,  147,  147,  309,  147,  149,  149,
      149,  309,  149,  309,  309,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  206,  309,  147,  211,  149,  309,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  309,  147,  246,  147,  147,  149,  250,  149,
      149,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  206,  147,  211,  149,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,    0,  309,
      309,  309,  309
    } ;

static const flex_int16_t yy_nxt[1069] =
    {   0,
       10,   11,   10,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       28,   28,   29,   30,   31,   32,   33,   34,   35,   35,
       35,   36,   35,   37,   35,   38,   35,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   35,
       51,   35,   52,   35,   53,   54,   55,   56,   35,   57,
       35,   58,   35,   59,   60,   61,   62,   63,   66,   66,
       68,   68,   85,   88,   89,  162,   91,  308,   67,   67,
       90,   90,   90,   90,   92,   86,  104,  105,  107,  108,
      117,  124,  121,  126,  118,  122,  130,  119,  127,  307,

      128,  125,  131,  132,  142,  143,  306,  133,   69,   69,
       71,   71,   72,  305,   71,   71,   73,   71,   71,   71,
       71,   71,   71,   71,   71,   73,   73,   73,   73,   71,
       71,   71,   74,   71,   71,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   71,   75,   71,   71,   71,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,  304,   71,  176,   71,   80,   80,   81,  177,   80,
       80,   82,   80,   80,   80,   80,   80,   80,   80,   80,
       81,   81,   81,   81,   80,   80,   80,   83,   80,   80,

       81,   81,   81,   81,   81,   81,   81,   81,   81,   80,
       84,   80,   80,   80,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,  297,   80,   81,   80,
       93,  137,   94,   95,   95,   95,  150,   93,  273,  101,
      101,  101,  101,   96,   97,  139,  138,  295,   98,  140,
       99,   97,   73,  184,  273,  100,  148,   96,  156,  156,
       97,  185,  102,  152,  152,  152,  152,   97,  303,   98,
       90,   90,   90,   90,  302,   97,   99,  160,  160,  160,
      172,  157,   97,  173,  174,   93,  153,   94,   95,   95,

       95,   97,   93,  301,   95,   95,   95,   95,   97,   97,
      161,  164,  165,  165,  165,  197,   97,  156,  156,  198,
      100,  166,  166,  166,  166,   97,  182,  155,  158,  300,
      158,  183,   97,  159,  159,  159,  159,   93,  193,  101,
      101,  101,  101,  194,  152,  152,  152,  152,  160,  160,
      160,   97,  165,  165,  165,  165,  159,  159,  159,  159,
      246,  249,  102,  299,  247,  250,  298,   97,  204,  246,
      205,  205,  206,  247,  205,  205,  204,  205,  205,  205,
      205,  205,  205,  205,  205,  204,  204,  204,  204,  205,
      205,  205,  207,  205,  205,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  205,  208,  205,  205,  205,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  297,  205,  295,  205,  209,  249,  210,  210,  209,
      250,  210,  210,  211,  210,  210,  210,  210,  210,  210,
      210,  210,  209,  209,  209,  209,  210,  210,  210,  212,
      210,  210,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  210,  213,  210,  210,  210,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  293,  210,

      292,  210,  152,  152,  152,  152,  156,  156,  214,  214,
      214,  214,  291,  290,   97,  160,  160,  160,   93,  289,
       94,   95,   95,   95,  288,  153,  287,  286,  285,  157,
       97,  215,   97,  214,  214,  214,  214,   93,  161,   95,
       95,   95,   95,  100,  214,  214,  214,  214,   97,  284,
       93,   97,  101,  101,  101,  101,  215,  283,  282,  273,
      273,  272,  155,  271,   97,  270,  269,   97,  268,  267,
      266,  265,  264,  263,  262,  102,  261,  260,  259,  258,
       97,  204,  257,  204,  204,  204,  245,  204,  204,  204,
      256,  204,  204,  204,  204,  204,  204,  204,  204,  255,

      254,  253,  252,  204,  204,  204,  204,  204,  204,  251,
      210,  205,  244,  243,  242,  241,  240,  239,  204,  204,
      204,  204,  204,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  204,  204,  204,  204,  209,
      216,  209,  209,  209,  309,  209,  209,  209,  248,  209,
      209,  209,  209,  209,  209,  209,  209,  163,  146,  146,
      203,  209,  209,  209,  209,  209,  209,  202,  201,  200,
      199,  196,  195,  192,  191,  190,  209,  209,  209,  209,
      209,  189,  188,  187,  186,  181,  180,  179,  178,  175,

      171,  170,  169,  168,  167,  163,  154,  151,   80,  149,
      146,  146,   77,  209,  209,  209,  209,  204,  247,  204,
      274,  274,  275,  204,  274,  274,  247,  274,  274,  274,
      274,  274,  274,  274,  274,  247,  247,  247,  247,  274,
      274,  274,  276,  274,  274,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  274,  277,  274,  274,  274,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  204,  274,  204,  274,  209,  249,  209,  278,  278,
      249,  209,  278,  278,  279,  278,  278,  278,  278,  278,

      278,  278,  278,  249,  249,  249,  249,  278,  278,  278,
      280,  278,  278,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  278,  281,  278,  278,  278,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  209,
      278,  209,  278,  247,   71,  247,  247,  247,  294,  247,
      247,  247,  146,  247,  247,  247,  247,  247,  247,  247,
      247,  147,  146,  145,  144,  247,  247,  247,  247,  247,
      247,  141,  136,  135,  134,  129,  123,  120,  116,  115,
      247,  247,  247,  247,  247,  114,  113,  112,  111,  109,

      106,  103,   87,   79,   78,   77,   70,  309,   65,   65,
      309,  309,  309,  309,  309,  309,  309,  247,  247,  247,
      247,  249,  309,  249,  249,  249,  309,  249,  249,  249,
      296,  249,  249,  249,  249,  249,  249,  249,  249,  309,
      309,  309,  309,  249,  249,  249,  249,  249,  249,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  249,  249,
      249,  249,  249,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  249,  249,  249,  249,   64,
       64,   64,   64,   76,  309,   76,   76,  110,  110,    9,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309
    } ;

static const flex_int16_t yy_chk[1069] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    6,
        7,    8,   21,   24,   24,  313,   26,  303,    5,    6,
       25,   25,   25,   25,   26,   21,   31,   31,   33,   33,
       44,   48,   46,   49,   44,   46,   51,   44,   49,  301,

       49,   48,   51,   51,   58,   58,  300,   51,    7,    8,
       14,   14,   14,  299,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,  298,   14,  118,   14,   18,   18,   18,  118,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,

       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,  297,   18,   84,   18,
       27,   55,   27,   27,   27,   27,   84,   28,  296,   28,
       28,   28,   28,   27,   27,   56,   55,  295,   27,   56,
       27,   28,   75,  124,  294,   27,   75,   27,   96,   96,
       27,  124,   28,   90,   90,   90,   90,   28,  292,   27,
       93,   93,   93,   93,  288,   90,   27,   98,   98,   98,
      116,   96,   93,  116,  116,   94,   90,   94,   94,   94,

       94,   90,   95,  286,   95,   95,   95,   95,   93,   94,
       98,  100,  100,  100,  100,  139,   95,  157,  157,  139,
       94,  102,  102,  102,  102,   94,  123,   95,   97,  284,
       97,  123,   95,   97,   97,   97,   97,  101,  135,  101,
      101,  101,  101,  135,  153,  153,  153,  153,  161,  161,
      161,  101,  155,  155,  155,  155,  158,  158,  158,  158,
      208,  213,  101,  283,  208,  213,  282,  101,  147,  277,
      147,  147,  147,  277,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,

      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  280,  147,  276,  147,  149,  281,  149,  149,  149,
      281,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  270,  149,

      266,  149,  152,  152,  152,  152,  156,  156,  159,  159,
      159,  159,  265,  264,  152,  160,  160,  160,  164,  263,
      164,  164,  164,  164,  262,  152,  261,  260,  255,  156,
      152,  159,  164,  214,  214,  214,  214,  165,  160,  165,
      165,  165,  165,  164,  215,  215,  215,  215,  164,  254,
      166,  165,  166,  166,  166,  166,  214,  253,  252,  248,
      245,  244,  165,  242,  166,  241,  240,  165,  239,  238,
      236,  235,  234,  233,  231,  166,  230,  227,  226,  225,
      166,  206,  224,  206,  206,  206,  206,  206,  206,  206,
      223,  206,  206,  206,  206,  206,  206,  206,  206,  222,

      221,  220,  219,  206,  206,  206,  206,  206,  206,  216,
      212,  207,  203,  202,  201,  199,  198,  197,  206,  206,
      206,  206,  206,  196,  195,  193,  192,  191,  190,  189,
      187,  186,  185,  184,  181,  180,  179,  178,  177,  176,
      174,  173,  172,  171,  170,  206,  206,  206,  206,  211,
      169,  211,  211,  211,  163,  211,  211,  211,  211,  211,
      211,  211,  211,  211,  211,  211,  211,  162,  150,  148,
      144,  211,  211,  211,  211,  211,  211,  143,  142,  141,
      140,  138,  137,  134,  131,  129,  211,  211,  211,  211,
      211,  128,  127,  126,  125,  122,  121,  120,  119,  117,

      113,  112,  111,  108,  104,   99,   91,   85,   83,   82,
       81,   80,   76,  211,  211,  211,  211,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  275,   74,  275,  275,  275,  275,  275,
      275,  275,   73,  275,  275,  275,  275,  275,  275,  275,
      275,   72,   71,   61,   59,  275,  275,  275,  275,  275,
      275,   57,   54,   53,   52,   50,   47,   45,   43,   42,
      275,  275,  275,  275,  275,   40,   38,   37,   36,   34,

       32,   29,   22,   17,   16,   15,   13,    9,    4,    3,
        0,    0,    0,    0,    0,    0,    0,  275,  275,  275,
      275,  279,    0,  279,  279,  279,    0,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,    0,
        0,    0,    0,  279,  279,  279,  279,  279,  279,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  279,  279,
      279,  279,  279,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  279,  279,  279,  279,  310,
      310,  310,  310,  311,    0,  311,  311,  312,  312,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[104] =
    {   0,
0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 
    1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include<bits/stdc++.h>
using namespace std;
stack<int> indent_cnt;
int ns = 0;
#include "helper.hpp"
#include "parser.tab.h"
int eof = 0;
#line 817 "lex.yy.c"
/*INTEGER*/
/* FLOAT */
/* STRING */
/* Operators */
/* DELIMITER */
/* DUNDERS */                       
/* HELPER */            
/*KEYWORDS*/
/* Bool */
/* IDENTIFIERS */

#line 829 "lex.yy.c"

#define INITIAL 0
#define indent_state 1
#define implicit1 2
#define implicit2 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 160 "lexer.l"

#line 1051 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 310 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1000 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(indent_state):
case YY_STATE_EOF(implicit1):
case YY_STATE_EOF(implicit2):
#line 161 "lexer.l"
{
    if(eof == 0){
        unput('\n');
        eof = 1;
    }
    else{
        yyterminate();
    }
}
	YY_BREAK
case 1:
YY_RULE_SETUP
#line 170 "lexer.l"
{
	unput(yytext[0]);
	if(ns > indent_cnt.top()){
		indent_cnt.push(ns);
		BEGIN(INITIAL);
        return INDENT;
	}
	else if(ns == indent_cnt.top()){
		BEGIN(INITIAL);
	}
	else{
		indent_cnt.pop();
        if (ns > indent_cnt.top()) {
            cout << "Indentation error at line number " << yylineno << "\n";
        }
        return DEDENT;
	}
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 189 "lexer.l"
{
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 192 "lexer.l"
{
    BEGIN(INITIAL);
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    return RIGHTBRACKET;
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 198 "lexer.l"
{
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 201 "lexer.l"
{
    BEGIN(INITIAL);
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    return RIGHTSQUAREBRACKET;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 208 "lexer.l"
{
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    return RANGE;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 213 "lexer.l"
{
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    return PRINT;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 219 "lexer.l"
{

    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    return UNDERSCORE;
}  
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 226 "lexer.l"
{
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    return INTEGER;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 232 "lexer.l"
{
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    return FLOAT;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 238 "lexer.l"
{
    ////cout<<"PLUS\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    return PLUS;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 244 "lexer.l"
{
    ////cout<<"MINUS\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return MINUS;
}           
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 250 "lexer.l"
{
    ////cout<<"MULTIPLY\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    return MULTIPLY;
}       
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 256 "lexer.l"
{
    ////cout<<"EXP\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    return EXP;
}        
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 262 "lexer.l"
{
    ////cout<<"DIVIDE\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return DIVIDE;
}          
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 268 "lexer.l"
{
   // //cout<<"DIVIDEDIVIDE\n";
   yylval.lex = string(yytext); 
   yylval.lineno = yylineno;
   return DIVIDEDIVIDE;
}    
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 274 "lexer.l"
{
    ////cout<<"MOD\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return MOD;
}             
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 280 "lexer.l"
{
    //cout<<"AT\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return AT;
}              
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 286 "lexer.l"
{
    ////cout<< "RIGHTSHIFT\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return RIGHTSHIFT;
}      
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 292 "lexer.l"
{
    ////cout<<"LEFTSHIFT\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return LEFTSHIFT;
}       
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 298 "lexer.l"
{
    ////cout<< "AMPERSAND\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return AMPERSAND;
}       
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 304 "lexer.l"
{
    //cout<<"EQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return EQUAL;
}           
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 310 "lexer.l"
{
    ////cout<<"NOTEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return NOTEQUAL;
}        
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 316 "lexer.l"
{
    ///cout<<"GREATER\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return GREATER;
}         
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 322 "lexer.l"
{
    //cout<<"LESS\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return LESS;
}            
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 328 "lexer.l"
{
    //cout<<"GREATEREQ\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return GREATEREQ;
}       
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 334 "lexer.l"
{
    //cout<<"LESSEQ\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return LESSEQ;
}          
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 340 "lexer.l"
{
    //cout<<"BITOR\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return BITOR;
}           
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 346 "lexer.l"
{
    //cout<<"BITXOR\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return BITXOR;
}          
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 352 "lexer.l"
{
    //cout<<"BITNOT\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return BITNOT;
}          
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 358 "lexer.l"
{
    //cout<<"ASSIGN\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return ASSIGN;
}          
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 364 "lexer.l"
{
    //cout<<"PLUSEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return PLUSEQUAL;
}       
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 370 "lexer.l"
{
    //cout<<"MINUSEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return MINUSEQUAL;
}      
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 376 "lexer.l"
{
    //cout<<"MULTIPLYEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return MULTIPLYEQUAL;
}  
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 382 "lexer.l"
{
    //cout<<"DIVIDEEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return DIVIDEEQUAL;
}    
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 388 "lexer.l"
{
    //cout<<"MODEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return MODEQUAL;
}   
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 394 "lexer.l"
{
    //cout<<"EXPONENTEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return EXPONENTEQUAL;
}  
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 400 "lexer.l"
{
    //cout<<"ANDEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return ANDEQUAL;
}       
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 406 "lexer.l"
{
    //cout<<"OREQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return OREQUAL;
}         
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 412 "lexer.l"
{
    //cout<<"XOREQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return XOREQUAL;
}        
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 418 "lexer.l"
{
    //cout<<"LEFTSHIFTEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return LEFTSHIFTEQUAL;
} 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 424 "lexer.l"
{
    //cout<<"RIGHTSHIFTEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return RIGHTSHIFTEQUAL;
} 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 430 "lexer.l"
{
    //cout<<"COLONEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return COLONEQUAL;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 436 "lexer.l"
{
    //cout<<"LEFTBRACKET\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    BEGIN(implicit1);
   return LEFTBRACKET;
}        
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 443 "lexer.l"
{
    //cout<<"RIGHTBRACKET\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return RIGHTBRACKET;
}       
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 449 "lexer.l"
{
    //cout<<"LEFTSQUAREBRACKET\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    BEGIN(implicit2);
   return LEFTSQUAREBRACKET;
}  
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 456 "lexer.l"
{
    //cout<<"RIGHTSQUAREBRACKET\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return RIGHTSQUAREBRACKET;
} 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 462 "lexer.l"
{
    //cout<<"LEFTCURLYBRACKET\n"; 
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return LEFTCURLYBRACKET; 
}   
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 468 "lexer.l"
{
    //cout<<"RIGHTCURLYBRACKET\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return RIGHTCURLYBRACKET; 
}  
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 474 "lexer.l"
{
    //cout<<"COMMA\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return COMMA;
}              
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 480 "lexer.l"
{
    //cout<<"COLON\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return COLON;
}              
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 486 "lexer.l"
{
    //cout<<"SEMICOLON\n"; 
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return SEMICOLON;
}          
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 492 "lexer.l"
{
        //cout<<"DOT\n";
        yylval.lex = string(yytext); 
        yylval.lineno = yylineno;
       return DOT;
}                
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 498 "lexer.l"
{
    //cout<<"ARROW\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return ARROW;
}              
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 504 "lexer.l"
{
    //cout<<"DIVIDEDIVIDEEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return DIVIDEDIVIDEEQUAL;
}  
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 510 "lexer.l"
{
    //cout<<"ATEQUAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return ATEQUAL;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 517 "lexer.l"
{
    //cout <<"NAME_DUNDER\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return NAME;
}              
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 523 "lexer.l"
{
    //cout <<"MAIN_DUNDER\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return NAME;
}            
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 529 "lexer.l"
{
    //cout <<"INIT_DUNDER\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return NAME;
}         
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 535 "lexer.l"
{
    //cout <<"BACKSLASH\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return BACKSLASH;
}                                  
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 541 "lexer.l"
{
    //cout <<"FALSE\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return FALSE;
}      
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 547 "lexer.l"
{
    // cout <<"AWAIT\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return AWAIT;
}      
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 553 "lexer.l"
{
    // cout <<"ELSE\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return ELSE;
}     
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 559 "lexer.l"
{
   // cout <<"IMPORT\n";
   return IMPORT;
}    
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 563 "lexer.l"
{
    // cout <<"PASS\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return PASS;
}       
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 569 "lexer.l"
{
   // cout <<"NONE\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return NONE;
}       
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 575 "lexer.l"
{
    // cout <<"BREAK\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return BREAK;
}      
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 581 "lexer.l"
{
    // cout <<"EXCEPT\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return EXCEPT;
}     
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 587 "lexer.l"
{
    // cout <<"IN\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return IN;
}         
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 593 "lexer.l"
{
    // cout <<"RAISE\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return RAISE;
}      
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 599 "lexer.l"
{
    //cout<<"TRUE\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return TRUE;
}       
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 605 "lexer.l"
{
    //cout<<"CLASS\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return CLASS;
}     
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 611 "lexer.l"
{
    //cout<<"FINALLY\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return FINALLY;
}    
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 617 "lexer.l"
{
    //cout<<"IS\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return IS;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 624 "lexer.l"
{
    //cout<< "RETURN\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
    return RETURN;
}     
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 630 "lexer.l"
{
    //cout<<"AND\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return AND;
}       
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 636 "lexer.l"
{
    //cout <<"CONTINUE\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return CONTINUE;
}   
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 642 "lexer.l"
{
    //cout <<"FOR\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return FOR;
}       
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 648 "lexer.l"
{
    //cout <<"LAMBDA\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return LAMBDA;
}    
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 654 "lexer.l"
{
    //cout <<"TRY\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return TRY;
}       
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 660 "lexer.l"
{
    //cout <<"AS\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return AS;
}        
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 666 "lexer.l"
{
    //cout <<"DEF\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return DEF;
}              
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 672 "lexer.l"
{
    // cout <<"FROM\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return FROM;
}            
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 678 "lexer.l"
{
    // cout <<"NONLOCAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return NONLOCAL;
}     
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 684 "lexer.l"
{
    // cout <<"WHILE\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return WHILE;
}     
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 690 "lexer.l"
{
    // cout <<"ASSERT\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return ASSERT;
}        
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 696 "lexer.l"
{
    // cout <<"DEL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return DEL;
}             
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 702 "lexer.l"
{
    // cout <<"GLOBAL\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return GLOBAL;
}        
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 708 "lexer.l"
{
    // cout <<"NOT\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return NOT;
}               
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 714 "lexer.l"
{
    // cout <<"WITH\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return WITH;
}      
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 720 "lexer.l"
{
    // cout <<"ASYNC\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return ASYNC;
}           
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 726 "lexer.l"
{
    // cout <<"ELIF\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return ELIF;
}             
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 732 "lexer.l"
{
    // cout <<"IF\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return IF;
}                 
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 738 "lexer.l"
{
    // cout <<"OR\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return OR;
}                 
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 744 "lexer.l"
{
    // cout <<"YIELD\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return YIELD;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 750 "lexer.l"
{
    //cout << "NAME\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return NAME;
}
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 757 "lexer.l"
{
    //cout<<"STRING\n";
    yylval.lex = string(yytext); 
    yylval.lineno = yylineno;
   return STRING;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 764 "lexer.l"
{
    // cout << "SPACE\n";
    //strcpy(yylval.tok.lex, yytext); 
}
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 768 "lexer.l"
{

}
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 772 "lexer.l"
{
    char ch = yyinput();
    ns = 0;
	while(ch ==' ' || ch == '\n'){
		if(ch == '\n'){
                        ns = 0;
                }
		if(ch == ' ') ns++;
		ch = yyinput();
	}

	unput(ch);
    BEGIN(indent_state);
    return NEWLINE;
}
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 788 "lexer.l"
{
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 791 "lexer.l"
{
    if(yytext[0]!=0) {
    cerr << "Invalid character " << int(yytext[0]) << " at line number " << yylineno << "\n";
    exit(1);
    }
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 798 "lexer.l"
ECHO;
	YY_BREAK
#line 2164 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 310 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 310 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 309);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 798 "lexer.l"

int yywrap(){
   return 1;
}

